### ISSUE TITLE
textfield not working?

### ISSUE THREAD

**Issue by bachig26** [therealFoxster/altsource-viewer#3]
when I tried to view the source file by inputing the Source URL (example: https://raw.githubusercontent.com/arichorn/arichorn.github.io/main/apps.json) in the search text field, it doesn't work and there were no response from it.

I need to manually use the browser address bar to access the Source View (https://therealfoxster.github.io/altsource-viewer/index.html?source=https://raw.githubusercontent.com/arichorn/arichorn.github.io/main/apps.json).

Please have a look into this. I'm not sure if it's the search function already implemented or not but looking at the webpage html, it doesn't seem to have the search function.

If it's not present now, will it be available in future?

### Screenshot:
![ipSP7uhu1i](https://github.com/therealFoxster/altsource-viewer/assets/96393348/5588c675-a7f9-4a38-93e4-00a2e2f6a990)

**Comment by therealFoxster** [comment]
Thanks for reporting! It was just a missing import that broke the page redirection after you hit enter. It should be fixed now.
