### ISSUE TITLE
`TypeError: app.tintColor is undefined` error when app does not specify `tintColor`

### ISSUE THREAD

**Issue by DetachHead** [therealFoxster/altsource-viewer#4]
![image](https://github.com/therealFoxster/altsource-viewer/assets/57028336/75ed6de2-80e0-4584-a15e-51d5a14f87eb)

`tintColor` is optional according to the [altstore source docs](https://faq.altstore.io/distribute-your-apps/make-a-source#tintcolor-string)

**Comment by therealFoxster** [comment]
Thanks for reporting! 1e0d298 should address this. Lmk if it's still an issue

**Comment by DetachHead** [comment]
thanks! now i get this error:

![image](https://github.com/therealFoxster/altsource-viewer/assets/57028336/bf9f8084-0e91-41b6-bf68-cc5d2db9aa67)

i think `screenshotURLs` was removed from the docs and was replaced by `screenshots` (which is still optional) https://faq.altstore.io/distribute-your-apps/make-a-source#screenshots-array-of-screenshots

**Comment by therealFoxster** [comment]
Dang I wasn't aware of all these changes they made. Anyway hopefully 21f0b3d addresses this. Lmk if it still doesn't

**Comment by DetachHead** [comment]
all good now, thanks!
