### ISSUE TITLE
[Bug] "TypeError: app.appPermissions.privacy.forEach is not a function" error when trying to preview YTLitePlus source.

### ISSUE THREAD

**Issue by Balackburn** [therealFoxster/altsource-viewer#5]
I suppose the error is mine but I can't preview YTLitePlus with your viewer, the source preview works but not the app preview.

See yourself : 

https://therealfoxster.github.io/altsource-viewer/view/app/?source=https://raw.githubusercontent.com/YTLitePlus/YTLitePlus-Altstore/main/apps.json&id=com.google.ios.youtube

The source is : https://raw.githubusercontent.com/YTLitePlus/YTLitePlus-Altstore/main/apps.json

Thank you.

**Comment by therealFoxster** [comment]
Thanks for reporting! I didn't realize they switched to a new JSON format (again). I was following the format on https://cdn.altstore.io/file/altstore/apps.json, where `appPermissions` are listed like this:

```json
"appPermissions": {
  "entitlements": [
    {
      "name": "get-task-allow"
    },
  ],
  "privacy": [
    {
      "name": "Microphone",
      "usageDescription": "Delta uses your microphone to emulate the Nintendo DS microphone."
     }
  ],
}
```

However, according to https://faq.altstore.io/distribute-your-apps/make-a-source#app-permissions, they should look something like:

```json
"appPermissions": {
  "entitlements": [
    "get-task-allow"
  ],
  "privacy": {
    "NSMicrophoneUsageDescription": "Delta uses your microphone to emulate the Nintendo DS microphone."
  },
}
```

Regardless, e40159e should add support for both formats.

**Comment by Balackburn** [comment]
Thank you!
